#ifdef _NAV_FFMPEG_VERSION

#ifndef _NAV_FFMPEG_CAT
#define _NAV_FFMPEG_CAT(x, y) x##y
#endif

#ifndef _NAV_FFMPEG_NAMESPACE_0
#define _NAV_FFMPEG_NAMESPACE_0(x) _NAV_FFMPEG_CAT(ffmpeg, x)
#endif

#ifndef _NAV_FFMPEG_PREFIX_0
#define _NAV_FFMPEG_PREFIX_0(x) _NAV_FFMPEG_CAT(FFmpeg, x)
#endif

#ifndef _NAV_FFMPEG_DISABLEMENT_0
#define _NAV_FFMPEG_DISABLEMENT_0(x) _NAV_FFMPEG_CAT(FFMPEG, x)
#endif

#ifdef _NAV_FFMPEG_NAMESPACE
#undef _NAV_FFMPEG_NAMESPACE
#endif
#define _NAV_FFMPEG_NAMESPACE _NAV_FFMPEG_NAMESPACE_0(_NAV_FFMPEG_VERSION)

#ifdef _NAV_FFMPEG_PREFIX_1
#undef _NAV_FFMPEG_PREFIX_1
#endif
#define _NAV_FFMPEG_PREFIX_1 _NAV_FFMPEG_PREFIX_0(_NAV_FFMPEG_VERSION)

#ifdef _NAV_FFMPEG_PREFIX
#undef _NAV_FFMPEG_PREFIX
#endif
#define _NAV_FFMPEG_PREFIX(x) _NAV_FFMPEG_CAT(_NAV_FFMPEG_PREFIX_1, x)

#ifdef _NAV_FFMPEG_DISABLEMENT
#undef _NAV_FFMPEG_DISABLEMENT
#endif
#define _NAV_FFMPEG_DISABLEMENT NAV_STRINGIZE(_NAV_FFMPEG_DISABLEMENT_0(_NAV_FFMPEG_VERSION))

#endif
