name: Build
on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        PLATFORM: [x64, ARM64]
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure
      run: cmake -Bbuild -S. -A ${{ matrix.PLATFORM }} --install-prefix %CD%\install -DBUILD_SHARED_LIBS=1
    - name: Install
      run: cmake --build build --config RelWithDebInfo --target install
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nav-dll-${{ matrix.PLATFORM }}
        path: install/
        compression-level: 9
