name: Doxygen
on:
  push:
    branches: [main]
  release:
    types: [released]

concurrency:
  group: "docs"
  cancel-in-progress: false

jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main Repository
      uses: actions/checkout@v4
      with:
        path: nav
        fetch-depth: 2
    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        path: docs
        ref: gh-pages
    - name: Generate Documentation
      uses: mattnotmitt/doxygen-action@1.9.8
      with:
        working-directory: nav
    - name: Cleanup Branch
      if: github.event_name == 'push'
      run:
        rm -rf docs/${{ github.ref_name }}
    - name: Move Generated Docs
      run: sudo mv nav/docs/html docs/${{ github.ref_name }}
    - name: Add and Commit
      uses: EndBug/add-and-commit@v9
      with:
        cwd: docs
        add: ${{ github.ref_name }}
        default_author: github_actions
        message: 'Build ${{ github.sha }} of ${{ github.ref_name }}'
        push: true
